### PR TITLE
Superficial deemix bug patch

### PR DESCRIPTION
**Pull request by trailfog**
This is a simple and superficial bug patch for deemix, as it does not seem to be getting any updates any more.

The issue is described in #63, where when fetching the `newRelease` endpoint from the deemix-gui server, the entire server will crash due to some missing data not being sent to deezer.

To patch this issue, the `bockiii/deemix-docker` image has been removed and deemix gets built directly from source in this Dockerfile.

Once the deemix-gui repo has patched the bug, the `sed` command can safely be removed.

### CODE REVIEW

**Comment by robbtate** [comment]
I've gave up on this sinking ship and moved to unmanic. It works great, download artists/albums/songs/playlist straight from deemix and unmanic transcodes from flac to MP3 in the same folder. No faffing around it just works.

**Comment by mon5termatt** [comment]
@youegraillot can we get this merged, pretty please :D

**Comment by mbc0** [comment]
Hi, If I install the latest lidarr-on-steroids does it include the deemix bug patch?  Thank you

**Comment by youegraillot** [comment]
Hey, sorry for not being responsive on this image anymore
I don't have much time to maintain this project on a regular basis :(
I'll merge !

**Comment by youegraillot** [comment]
@trailfog 
PR broke the build from github action
I tried to fix it for a bit but could not figure out why it builds locally but not on github action

**Comment by trailfog** [comment]
@youegraillot I'll have a look at it. It seems to me, that the arm version of the build is failing. The amd version builds just fine in the pipeline.

Btw, you can use something like [act](https://github.com/nektos/act) to run & debug your GitHub actions locally ;)

**Comment by trailfog** [comment]
@youegraillot I have fixed the issue on the arm64 build.

I'm not going to open another pull request for this, you can copy & paste the change I made here: https://github.com/trailfog/lidarr-on-steroids/commit/fb7682006f9f590d56589f2cf289a70da5e7b111

For some reason, the alpine image requires some additional dependencies when run on an arm processor.
I hope this will fix the issue, it does locally for me at least.

**Comment by noworthwhile** [comment]
Build on RaspberryPi fails with exit code 1 on "run yarn dist-server"

`#7 109.2 asset app.js 1.66 MiB [emitted] [minimized] (name: main) 1 related asset
#7 109.2 orphan modules 9.42 KiB [orphan] 14 modules
#7 109.2 runtime modules 1.04 KiB 5 modules
#7 109.2 modules by path ./node_modules/ 3.23 MiB
#7 109.2   javascript modules 2.85 MiB 543 modules
#7 109.2   json modules 392 KiB
#7 109.2     modules by path ./node_modules/iconv-lite/ 86.7 KiB 8 modules
#7 109.2     + 9 modules
#7 109.2 modules by path ./src/ 94.1 KiB
#7 109.2   modules by path ./src/routes/ 56.2 KiB 36 modules
#7 109.2   modules by path ./src/helpers/*.ts 8.82 KiB 7 modules
#7 109.2   modules by path ./src/websocket/ 3.05 KiB 6 modules
#7 109.2   modules by path ./src/*.ts 26 KiB
#7 109.2     ./src/index.ts 1.53 KiB [built] [code generated]
#7 109.2     + 3 modules
#7 109.2 + 22 modules
#7 109.2 webpack 5.75.0 compiled successfully in 96320 ms
#7 111.2 $ yarn --cwd webui build
#7 112.1 $ npm-run-all --sequential clean build:js minify clean-temp
#7 113.8 $ rimraf public/js/bundle.js public/js/bundle.temp.js public/js/bundle.js.map
#7 115.0 $ rollup -c
#7 118.6 
#7 118.6 src/app.js → public/js/bundle.temp.js...
#7 130.3 Browserslist: caniuse-lite is outdated. Please run:
#7 130.3   npx update-browserslist-db@latest
#7 130.3   Why you should do it regularly: https://github.com/browserslist/update-db#readme
#7 166.1 -----------------------------
#7 166.1 Rollup File Analysis
#7 166.1 -----------------------------
#7 166.1 bundle size:    1.803 MB
#7 166.1 original size:  1.802 MB
#7 166.1 code reduction: 0 %
#7 166.1 module count:   308
#7 166.1 
#7 166.1 /node_modules/vue/dist/vue.esm.js
#7 166.1 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 15.28 % (275.481 KB)
#7 166.1 /node_modules/flag-icon-css/flags/4x3/rs.svg
#7 166.1 █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10.46 % (188.572 KB)
#7 166.1 /node_modules/flag-icon-css/flags/4x3/es.svg
#7 166.1 ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.26 % (94.763 KB)
#7 166.1 /src/components/pages/Settings.vue
#7 166.1 ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5.12 % (92.34 KB)
#7 166.1 /node_modules/vue-router/dist/vue-router.esm.js
#7 166.1 ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.22 % (76.086 KB)
#7 166.1 /node_modules/vue-i18n/dist/vue-i18n.esm.js
#7 166.1 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 3.24 % (58.335 KB)
#7 166.1 /src/assets/ar.svg
#7 166.1 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2.41 % (43.354 KB)
#7 166.1 /src/assets/deemix-icon.svg
#7 166.1 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2.37 % (42.668 KB)
#7 166.1 /node_modules/@vue/composition-api/dist/vue-composition-api.esm.js
#7 166.1 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2.28 % (41.07 KB)
#7 166.1 /node_modules/flag-icon-css/flags/4x3/hr.svg
#7 166.1 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2.27 % (40.845 KB)
#7 166.1 /node_modules/vuex/dist/vuex.esm.js
#7 166.1 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1.72 % (31.01 KB)
#7 166.1 /src/lang/fr.mjs
#7 166.1 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1.34 % (24.157 KB)
#7 166.1 /src/lang/el.mjs
#7 166.1 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1.29 % (23.234 KB)
#7 166.1 /src/styles/vendor/OpenSans.css
#7 166.1 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1.24 % (22.332 KB)
#7 166.1 /src/lang/de.mjs
#7 166.1 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1.22 % (22.066 KB)
#7 166.1 
#7 166.1 created public/js/bundle.temp.js in 47.5s
#7 167.2 $ esbuild public/js/bundle.temp.js --outfile=public/js/bundle.js --minify
#7 168.0 
#7 168.0   public/js/bundle.js  1.4mb ⚠️
#7 168.0 
#7 168.9 $ rimraf public/js/bundle.temp.js
#7 172.4 > pkg@5.8.1
#7 172.5 > Fetching base Node.js binaries to PKG_CACHE_PATH
#7 177.2 
#7 177.2 
#7 181.4 
#7 181.4 
#7 256.9 node:internal/child_process:420
#7 256.9     throw errnoException(err, 'spawn');
#7 256.9     ^
#7 256.9 
#7 256.9 Error: spawn Unknown system error -8
#7 256.9     at ChildProcess.spawn (node:internal/child_process:420:11)
#7 256.9     at spawn (node:child_process:733:9)
#7 256.9     at fabricate (/deemix-gui/node_modules/pkg/lib-es5/fabricator.js:55:51)
#7 256.9     at fabricateTwice (/deemix-gui/node_modules/pkg/lib-es5/fabricator.js:120:5)
#7 256.9     at MultiStream._queue (/deemix-gui/node_modules/pkg/lib-es5/producer.js:271:68)
#7 256.9     at MultiStream._next (/deemix-gui/node_modules/multistream/index.js:86:12)
#7 256.9     at Meter.onEnd (/deemix-gui/node_modules/multistream/index.js:129:12)
#7 256.9     at Object.onceWrapper (node:events:627:28)
#7 256.9     at Meter.emit (node:events:513:28)
#7 256.9     at endReadableNT (node:internal/streams/readable:1358:12) {
#7 256.9   errno: -8,
#7 256.9   code: 'Unknown system error -8',
#7 256.9   syscall: 'spawn'
#7 256.9 }
#7 257.0 error Command failed with exit code 1.
#7 257.0 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
process "/bin/sh -c yarn dist-server" did not complete successfully: exit code: 1`

**Comment by youegraillot** [comment]
@noworthwhile 
build is successful on github action with arm64
please use the dockerhub image or open a new ticket with more specific info on your hardware
closing

**Pull request merged**
