### PR TITLE
Add ARM64 support

### LINKED ISSUE #14: Does this work on linux arm?
Getting this error message;

exec /init: exec format error

### PR DESCRIPTION
**Pull request by themegaphoenix**
Fixes #14

### CODE REVIEW

**Comment by youegraillot** [comment]
Thanks !
Did you have time to try the resulting image ?

**Comment by themegaphoenix** [comment]
> Thanks ! Did you have time to try the resulting image ?

The image does start up but I am facing bug #16 so can't say it works for me

**Comment by themegaphoenix** [comment]
It seems the latest version of Deemix had breaking changes, which the plugin updated to and it broke:
https://github.com/ta264/Lidarr.Plugin.Deemix/releases/tag/v1.0.0.33

it now works

**Comment by youegraillot** [comment]
Awesome !
for clarity, I think we should revert the last changes (deemix update)
I'll commit the update afterward, by updating the hash in order to get constant builds

**Pull request merged**
